### ISSUE TITLE
rename object name

### ISSUE THREAD

**Issue by porres** [porres/pd-sfizz#1]
1st thing, the way it works now is that the object needs to be loaded as a "lib" via [declare].

I don't want this... I want just to load the external and that's it

I also want it to be renamed to "sfz~" to avoid conflicts to this one as Ill definitely change things and the functionality

I could not do any of this, can you help me figure it out @lucarda ?

**Comment by Lucarda** [comment]
@porres see #3 so we continue.

**Comment by porres** [comment]
done

**Comment by Lucarda** [comment]
I don't know yet how to start. will investigate.

**Comment by Lucarda** [comment]
there's a hack at #4 

please test

**Comment by porres** [comment]
nice, it works! Can we rename the help file to sfz~ now? Also, there seems to be more than one single file out there

**Comment by porres** [comment]
well, it's all ok I just hope you can help me rename the original file from "sfizz~-help" to "sfz~-help". Other than this, the object is already acceptable to be included in the ELSE library, I already did the main first changes... thanks @Lucarda

**Comment by porres** [comment]
if you can help me build for the other OSes other than mac, it'll be on the next release :)

**Comment by Lucarda** [comment]
> nice, it works! Can we rename the help file to sfz~ now?

are you doing all the steps as in https://github.com/porres/pd-sfizz/pull/4 description?

it should also rename the help patch.

**Comment by porres** [comment]
> it should also rename the help patch.

I know, but I don't a script to rename it, I want it to not need to be renamed at all, that is change the name on the source

**Comment by Lucarda** [comment]
i'll have to pull again but the windows build is not working anymore. I think I know how to fix it

**Comment by porres** [comment]
i deleted some folders that didn't seem to be needed, like "vst"m but I do have a larger size of this thing here, like 290MB instead of the 100 or so from the beggining. I guess I built some stuff that I can't get rid of anymore

**Comment by porres** [comment]
Anyway, I think we can merge this and get back into ELSE when you're done

**Comment by Lucarda** [comment]
Ok, ill try to fix the windows thing. then i want to try if i can strip the final object so that we reduce its size.

I didn't understand what you want for the help patch

**Comment by porres** [comment]
we have a help patch named "sfizz~-help.pd", I don't want that...

**Comment by Lucarda** [comment]
> I didn't understand what you want for the help patch

oh, you want to rename `pd-sfizz/sfizz~/sfizz~-help.pd` ?

**Comment by porres** [comment]
yes

**Comment by Lucarda** [comment]
ok i'll do it.

are you done? if yes i pull and start working

**Comment by porres** [comment]
i'm done

**Comment by Lucarda** [comment]
i'm done via #7

**Comment by porres** [comment]
let's move it to else now

**Comment by Lucarda** [comment]
do i do it?

**Comment by Lucarda** [comment]
i did it via https://github.com/porres/pd-else/pull/1681
